# Generated by Django 3.2.10 on 2021-12-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='iamge',
            new_name='image',
        ),
    ]
